---
mcpServers:
  context7:
    url: "https://mcp.context7.com/mcp"
    transportType: streamable-http
    headersToForward:
      - "Authorization"
      - "X-User-Token"
      - "X-Agent-Token"
plainID:
  runtimeBaseURL: "http://${PLAINID_RUNTIME_HOST}:${PLAINID_RUNTIME_PORT}/api"
  toolsAsset: tools
  clientID: ${PLAINID_CLIENT_ID}
  clientSecret: ${PLAINID_CLIENT_SECRET}
  emptyOnError: false
  plugins:
    logger:
      enable: true
    presidio:
      enable: false
      analyzer_url: "http://${PRESIDIO_ANALYZER_HOST}:${PRESIDIO_ANALYZER_PORT}/analyze"
      anonymizer_url: "http://${PRESIDIO_ANONYMIZER_HOST}:${PRESIDIO_ANONYMIZER_PORT}/anonymize"
      threshold: 0.5
    dataFilter:
      enable: false
      authHeader: "X-User-Token"
      filterUrl: "http://${DATAFILTER_HOST}:${DATAFILTER_PORT}/resql"
      clientID: ${DATAFILTER_CLIENT_ID}
      clientSecret: ${DATAFILTER_CLIENT_SECRET}
      flags:
        emptyAllowedTreatAsPermitted: true
        ignoreRuntimeAllowedFields: true
        expandStarColumn: false
        oppositeColumnFilteringBehavior: true
        runtimeAllowedAsMasked: false
        runtimeCLSAsMasked: true
  headersToForward:
    - "Authorization"
    - "X-User-Token"
    - "X-Agent-Token"
mcpProxy:
  addr: :5432
  pingInterval: 10
